記述場所のミスだった An error occurred while loading ./spec/controllers/messages_controller_spec.rb. Failure/Error: config.include Devise::Test::ControllerHelpers, type: :controller
NameError:
  undefined local variable or method `config' for main:Object
# ./spec/rails_helper.rb:25:in `<top (required)>'
# ./spec/controllers/messages_controller_spec.rb:1:in `require'
# ./spec/controllers/messages_controller_spec.rb:1:in `<top (required)>'
No examples found.

Finished in 0.0004 seconds (files took 5.3 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples